# GENERATED by tools/generate_mavtable.py — do not edit by hand.
# Source: pymavlink ardupilotmega dialect, MAVLink 2.0 definitions (v20, MAVLINK20=1).
# Each entry: id: (name, crc_extra, [(wire_field, field_fmt), ...], xml_fields).
#   (wire_field, field_fmt) — WIRE order; field_fmt is the exact little-endian
#   struct format for that field ('16s' = char[16], '5H' = uint16_t[5], ...).
#   xml_fields — XML order (pymavlink constructor order).
TABLE = {
    0: ('HEARTBEAT', 50, [('custom_mode', 'I'), ('type', 'B'), ('autopilot', 'B'), ('base_mode', 'B'), ('system_status', 'B'), ('mavlink_version', 'B')], ['type', 'autopilot', 'base_mode', 'custom_mode', 'system_status', 'mavlink_version']),
    1: ('SYS_STATUS', 124, [('onboard_control_sensors_present', 'I'), ('onboard_control_sensors_enabled', 'I'), ('onboard_control_sensors_health', 'I'), ('load', 'H'), ('voltage_battery', 'H'), ('current_battery', 'h'), ('drop_rate_comm', 'H'), ('errors_comm', 'H'), ('errors_count1', 'H'), ('errors_count2', 'H'), ('errors_count3', 'H'), ('errors_count4', 'H'), ('battery_remaining', 'b')], ['onboard_control_sensors_present', 'onboard_control_sensors_enabled', 'onboard_control_sensors_health', 'load', 'voltage_battery', 'current_battery', 'battery_remaining', 'drop_rate_comm', 'errors_comm', 'errors_count1', 'errors_count2', 'errors_count3', 'errors_count4']),
    24: ('GPS_RAW_INT', 24, [('time_usec', 'Q'), ('lat', 'i'), ('lon', 'i'), ('alt', 'i'), ('eph', 'H'), ('epv', 'H'), ('vel', 'H'), ('cog', 'H'), ('fix_type', 'B'), ('satellites_visible', 'B'), ('alt_ellipsoid', 'i'), ('h_acc', 'I'), ('v_acc', 'I'), ('vel_acc', 'I'), ('hdg_acc', 'I'), ('yaw', 'H')], ['time_usec', 'fix_type', 'lat', 'lon', 'alt', 'eph', 'epv', 'vel', 'cog', 'satellites_visible', 'alt_ellipsoid', 'h_acc', 'v_acc', 'vel_acc', 'hdg_acc', 'yaw']),
    30: ('ATTITUDE', 39, [('time_boot_ms', 'I'), ('roll', 'f'), ('pitch', 'f'), ('yaw', 'f'), ('rollspeed', 'f'), ('pitchspeed', 'f'), ('yawspeed', 'f')], ['time_boot_ms', 'roll', 'pitch', 'yaw', 'rollspeed', 'pitchspeed', 'yawspeed']),
    33: ('GLOBAL_POSITION_INT', 104, [('time_boot_ms', 'I'), ('lat', 'i'), ('lon', 'i'), ('alt', 'i'), ('relative_alt', 'i'), ('vx', 'h'), ('vy', 'h'), ('vz', 'h'), ('hdg', 'H')], ['time_boot_ms', 'lat', 'lon', 'alt', 'relative_alt', 'vx', 'vy', 'vz', 'hdg']),
    36: ('SERVO_OUTPUT_RAW', 222, [('time_usec', 'I'), ('servo1_raw', 'H'), ('servo2_raw', 'H'), ('servo3_raw', 'H'), ('servo4_raw', 'H'), ('servo5_raw', 'H'), ('servo6_raw', 'H'), ('servo7_raw', 'H'), ('servo8_raw', 'H'), ('port', 'B'), ('servo9_raw', 'H'), ('servo10_raw', 'H'), ('servo11_raw', 'H'), ('servo12_raw', 'H'), ('servo13_raw', 'H'), ('servo14_raw', 'H'), ('servo15_raw', 'H'), ('servo16_raw', 'H')], ['time_usec', 'port', 'servo1_raw', 'servo2_raw', 'servo3_raw', 'servo4_raw', 'servo5_raw', 'servo6_raw', 'servo7_raw', 'servo8_raw', 'servo9_raw', 'servo10_raw', 'servo11_raw', 'servo12_raw', 'servo13_raw', 'servo14_raw', 'servo15_raw', 'servo16_raw']),
    46: ('MISSION_ITEM_REACHED', 11, [('seq', 'H')], ['seq']),
    42: ('MISSION_CURRENT', 28, [('seq', 'H'), ('total', 'H'), ('mission_state', 'B'), ('mission_mode', 'B')], ['seq', 'total', 'mission_state', 'mission_mode']),
    43: ('MISSION_REQUEST_LIST', 132, [('target_system', 'B'), ('target_component', 'B'), ('mission_type', 'B')], ['target_system', 'target_component', 'mission_type']),
    44: ('MISSION_COUNT', 221, [('count', 'H'), ('target_system', 'B'), ('target_component', 'B'), ('mission_type', 'B')], ['target_system', 'target_component', 'count', 'mission_type']),
    45: ('MISSION_CLEAR_ALL', 232, [('target_system', 'B'), ('target_component', 'B'), ('mission_type', 'B')], ['target_system', 'target_component', 'mission_type']),
    47: ('MISSION_ACK', 153, [('target_system', 'B'), ('target_component', 'B'), ('type', 'B'), ('mission_type', 'B')], ['target_system', 'target_component', 'type', 'mission_type']),
    51: ('MISSION_REQUEST_INT', 196, [('seq', 'H'), ('target_system', 'B'), ('target_component', 'B'), ('mission_type', 'B')], ['target_system', 'target_component', 'seq', 'mission_type']),
    49: ('GPS_GLOBAL_ORIGIN', 39, [('latitude', 'i'), ('longitude', 'i'), ('altitude', 'i'), ('time_usec', 'Q')], ['latitude', 'longitude', 'altitude', 'time_usec']),
    242: ('HOME_POSITION', 104, [('latitude', 'i'), ('longitude', 'i'), ('altitude', 'i'), ('x', 'f'), ('y', 'f'), ('z', 'f'), ('q', '4f'), ('approach_x', 'f'), ('approach_y', 'f'), ('approach_z', 'f'), ('time_usec', 'Q')], ['latitude', 'longitude', 'altitude', 'x', 'y', 'z', 'q', 'approach_x', 'approach_y', 'approach_z', 'time_usec']),
    73: ('MISSION_ITEM_INT', 38, [('param1', 'f'), ('param2', 'f'), ('param3', 'f'), ('param4', 'f'), ('x', 'i'), ('y', 'i'), ('z', 'f'), ('seq', 'H'), ('command', 'H'), ('target_system', 'B'), ('target_component', 'B'), ('frame', 'B'), ('current', 'B'), ('autocontinue', 'B'), ('mission_type', 'B')], ['target_system', 'target_component', 'seq', 'frame', 'command', 'current', 'autocontinue', 'param1', 'param2', 'param3', 'param4', 'x', 'y', 'z', 'mission_type']),
    76: ('COMMAND_LONG', 152, [('param1', 'f'), ('param2', 'f'), ('param3', 'f'), ('param4', 'f'), ('param5', 'f'), ('param6', 'f'), ('param7', 'f'), ('command', 'H'), ('target_system', 'B'), ('target_component', 'B'), ('confirmation', 'B')], ['target_system', 'target_component', 'command', 'confirmation', 'param1', 'param2', 'param3', 'param4', 'param5', 'param6', 'param7']),
    77: ('COMMAND_ACK', 143, [('command', 'H'), ('result', 'B'), ('progress', 'B'), ('result_param2', 'i'), ('target_system', 'B'), ('target_component', 'B')], ['command', 'result', 'progress', 'result_param2', 'target_system', 'target_component']),
    22: ('PARAM_VALUE', 220, [('param_value', 'f'), ('param_count', 'H'), ('param_index', 'H'), ('param_id', '16s'), ('param_type', 'B')], ['param_id', 'param_value', 'param_type', 'param_count', 'param_index']),
    20: ('PARAM_REQUEST_READ', 214, [('param_index', 'h'), ('target_system', 'B'), ('target_component', 'B'), ('param_id', '16s')], ['target_system', 'target_component', 'param_id', 'param_index']),
    23: ('PARAM_SET', 168, [('param_value', 'f'), ('target_system', 'B'), ('target_component', 'B'), ('param_id', '16s'), ('param_type', 'B')], ['target_system', 'target_component', 'param_id', 'param_value', 'param_type']),
    162: ('FENCE_STATUS', 189, [('breach_time', 'I'), ('breach_count', 'H'), ('breach_status', 'B'), ('breach_type', 'B'), ('breach_mitigation', 'B')], ['breach_status', 'breach_count', 'breach_type', 'breach_time', 'breach_mitigation']),
    147: ('BATTERY_STATUS', 154, [('current_consumed', 'i'), ('energy_consumed', 'i'), ('temperature', 'h'), ('voltages', '10H'), ('current_battery', 'h'), ('id', 'B'), ('battery_function', 'B'), ('type', 'B'), ('battery_remaining', 'b'), ('time_remaining', 'i'), ('charge_state', 'B'), ('voltages_ext', '4H'), ('mode', 'B'), ('fault_bitmask', 'I')], ['id', 'battery_function', 'type', 'temperature', 'voltages', 'current_battery', 'current_consumed', 'energy_consumed', 'battery_remaining', 'time_remaining', 'charge_state', 'voltages_ext', 'mode', 'fault_bitmask']),
    253: ('STATUSTEXT', 83, [('severity', 'B'), ('text', '50s'), ('id', 'H'), ('chunk_seq', 'B')], ['severity', 'text', 'id', 'chunk_seq']),
}

ID_TO_NAME = {
    0: 'HEARTBEAT',
    1: 'SYS_STATUS',
    20: 'PARAM_REQUEST_READ',
    22: 'PARAM_VALUE',
    23: 'PARAM_SET',
    24: 'GPS_RAW_INT',
    30: 'ATTITUDE',
    33: 'GLOBAL_POSITION_INT',
    36: 'SERVO_OUTPUT_RAW',
    42: 'MISSION_CURRENT',
    43: 'MISSION_REQUEST_LIST',
    44: 'MISSION_COUNT',
    45: 'MISSION_CLEAR_ALL',
    46: 'MISSION_ITEM_REACHED',
    47: 'MISSION_ACK',
    49: 'GPS_GLOBAL_ORIGIN',
    51: 'MISSION_REQUEST_INT',
    73: 'MISSION_ITEM_INT',
    76: 'COMMAND_LONG',
    77: 'COMMAND_ACK',
    147: 'BATTERY_STATUS',
    162: 'FENCE_STATUS',
    242: 'HOME_POSITION',
    253: 'STATUSTEXT',
}
