#!/usr/bin/env python3
"""
tools/generate_mavtable.py — regenerate bridge/_mavtable_gen.py from pymavlink.

Run (needs pymavlink installed, e.g. in a venv):
    MAVLINK20=1 python tools/generate_mavtable.py

The generated table is a FROZEN artifact: per message — id, name, the
per-message CRC_EXTRA signature, and (per field) the wire field name and its
EXACT struct format character (arrays expanded, e.g. '16s' for char[16]).
bridge/_mavlink_v2.py packs/parses from this table only (no runtime
pymavlink dependency).

Why this exists:
  * hehe's vendored shim used a placeholder CRC ("zero checksum ... SITL is
    lenient") — real ArduPilot firmware rejects that.
  * pymavlink's `native_format` uses single-char placeholders for array
    fields; the expanded layout lives in the precomputed `unpacker`.
  * the v10 dialect family lacks the v2 mission_type field on MISSION_*
    messages — the v20 (MAVLink 2.0) definitions are the correct wire format.

Every generated table is cross-checked here against pymavlink's own
`unpacker` format, and tests/test_mavcodec.py verifies frames byte-for-byte
against pymavlink before anything is trusted.
"""
import os
import sys

os.environ["MAVLINK20"] = "1"  # MUST be set before the dialect import

# v20 = MAVLink 2.0 message definitions — REQUIRED for the wire (see above).
from pymavlink.dialects.v20 import ardupilotmega as mod  # noqa: E402

NAMES = [
    "HEARTBEAT",                 # 0    in/out
    "SYS_STATUS",                # 1    in
    "GPS_RAW_INT",               # 24   in
    "ATTITUDE",                  # 30   in
    "GLOBAL_POSITION_INT",       # 33   in
    "SERVO_OUTPUT_RAW",          # 36   in (bench visibility)
    "MISSION_ITEM_REACHED",      # 32   in
    "MISSION_CURRENT",           # 37   in
    "MISSION_REQUEST_LIST",      # 43   out
    "MISSION_COUNT",             # 44   in/out
    "MISSION_CLEAR_ALL",         # 45   out
    "MISSION_ACK",               # 47   in
    "MISSION_REQUEST_INT",       # 51   in/out
    "GPS_GLOBAL_ORIGIN",         # 49   in
    "MISSION_ITEM_INT",          # 73   in/out
    "COMMAND_LONG",              # 76   out
    "COMMAND_ACK",               # 77   in
    "PARAM_VALUE",               # 22   in
    "PARAM_REQUEST_READ",        # 21   out
    "PARAM_SET",                 # 23   out
    "FENCE_STATUS",              # 82   in
    "BATTERY_STATUS",            # 147  in
    "STATUSTEXT",                # 253  in/out
]

TYPE_CHAR = {
    "uint8_t": "B", "int8_t": "b", "uint16_t": "H", "int16_t": "h",
    "uint32_t": "I", "int32_t": "i", "uint64_t": "Q", "int64_t": "q",
    "float": "f", "double": "d", "char": "c",
}


def main():
    lines = [
        "# GENERATED by tools/generate_mavtable.py — do not edit by hand.",
        "# Source: pymavlink ardupilotmega dialect, MAVLink 2.0 definitions (v20, MAVLINK20=1).",
        "# Each entry: id: (name, crc_extra, [(wire_field, field_fmt), ...], xml_fields).",
        "#   (wire_field, field_fmt) — WIRE order; field_fmt is the exact little-endian",
        "#   struct format for that field ('16s' = char[16], '5H' = uint16_t[5], ...).",
        "#   xml_fields — XML order (pymavlink constructor order).",
        "TABLE = {",
    ]
    seen = {}
    for name in NAMES:
        msgid = getattr(mod, "MAVLINK_MSG_ID_" + name)
        cls = getattr(mod, "MAVLink_" + name.lower() + "_message")
        assert cls.id == msgid, (name, cls.id, msgid)

        wire = list(cls.ordered_fieldnames)
        xml = list(cls.fieldnames)
        types = list(cls.fieldtypes)
        alen = list(cls.array_lengths)
        xml_idx = {f: i for i, f in enumerate(xml)}

        # build expanded per-field formats (arrays expanded: char[16] -> '16s')
        pairs = []
        for j, wf in enumerate(wire):
            i = xml_idx[wf]
            t = types[i]
            n = alen[j]  # array_lengths is WIRE-ordered (fieldtypes is XML-ordered)
            if t == "char":
                fchar = "%ds" % n          # char[N] -> bytes (pymavlink uses 'Ns')
            else:
                base = TYPE_CHAR[t]
                fchar = ("%d%s" % (n, base)) if n else base
            pairs.append((wf, fchar))

        # Cross-check: concatenating per-field formats must equal pymavlink's
        # precomputed unpacker format exactly.
        expanded = "".join(p[1] for p in pairs)
        unpacker_fmt = cls.unpacker.format.lstrip("<")
        assert expanded == unpacker_fmt, (
            name, expanded, unpacker_fmt)
        lines.append(
            "    %d: (%r, %d, %r, %r)," % (msgid, name, cls.crc_extra, pairs, xml)
        )
        seen[msgid] = name
    lines.append("}")
    lines.append("")
    lines.append("ID_TO_NAME = {")
    for mid in sorted(seen):
        lines.append("    %d: %r," % (mid, seen[mid]))
    lines.append("}")
    lines.append("")

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "bridge", "_mavtable_gen.py")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d messages, all formats cross-checked vs pymavlink unpacker)"
          % (out, len(seen)))


if __name__ == "__main__":
    sys.exit(main())
